name: Build SIMPLE & Run Tests (Linux/MacOS)

on:
  push:
  workflow_dispatch:

jobs:
  Build_coarray:
    name: Build SIMPLE with coarrays
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc gfortran cmake \
            liblzma-dev libtiff-dev libwebp-dev libfftw3-dev libjpeg-dev \
            gnuplot sqlite3 \
            libcurl4-openssl-dev libopenblas-dev liblapack-dev libarpack2-dev \
            mpich libmpich-dev libcoarrays-mpich-dev 
          which cafrun
          which caf
          which cafrun
          caf --show
          find /usr -name 'libcaf_mpi*' 2>/dev/null
          dpkg -L libcoarrays-openmpi-dev | grep caf_mpi

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install opencoarrays jbigkit python@3.10 fftw curl openblas lapack arpack

      - name: Build SIMPLE with coarrays
        run: |
          git clone https://github.com/hael/SIMPLE.git 
          cd SIMPLE
          ./compile_coarrays.sh

      - name: Test SIMPLE coarrays
        run: |
          export SIMPLE_EMAIL="my.name@uni.edu"
          export SIMPLE_QSYS="coarray"
          export SIMPLE_PATH="$GITHUB_WORKSPACE/SIMPLE/build"
          export PATH="$SIMPLE_PATH/scripts:$SIMPLE_PATH/bin:$PATH"
          simple_test_exec test=coarrays
