on: [push]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        # This ensures all subsequent "run" steps use the MSYS2 bash shell
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2 and Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64 # Modern Windows runtime (recommended)
          update: true
          install: >-
            make
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-gcc-fortran
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-git
            mingw-w64-ucrt-x86_64-curl
            mingw-w64-ucrt-x86_64-libtiff
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-xz
            mingw-w64-ucrt-x86_64-zstd
            mingw-w64-ucrt-x86_64-jbigkit
            mingw-w64-ucrt-x86_64-mman-win32
            mingw-w64-ucrt-x86_64-libwebp
            mingw-w64-ucrt-x86_64-libdeflate
            mingw-w64-ucrt-x86_64-fftw
            mingw-w64-ucrt-x86_64-libjpeg-turbo

      - name: Configure and Build
        shell: msys2 {0}
        run: |
          git clone https://github.com/hael/SIMPLE.git 
          cp simple_posix.c ./SIMPLE/src/fileio/
          cp simple_syslib.f90 ./SIMPLE/src/fileio/
          cp simple_syslib_tester.f90 ./SIMPLE/src/fileio/
          cp simple_fileio.f90 ./SIMPLE/src/fileio/
          cp simple_forked_process_tester.f90 ./SIMPLE/src/utils/
          cp starfile_filename.h ./SIMPLE/src/extlibs/starfile/
          cp simple_aff_prop.f90 ./SIMPLE/src/utils/clustering/
          cp starfile_filename.cpp ./SIMPLE/src/extlibs/starfile/
          cp starfile_table.cpp ./SIMPLE/src/extlibs/starfile/
          cp posix_stubs_win32.c ./SIMPLE/src/fileio/posix_stubs_win32.c
          cp symlink_stub.c ./SIMPLE/src/fileio/symlink_stub.c
          cp CMakeLists.txt ./SIMPLE/src/
          cp simple_ipc_tcp_socket.f90 ./SIMPLE/src/utils/comm/
          cp simple_ipc_mq_tester.f90 ./SIMPLE/src/utils/comm
          cp simple_ipc_mq.f90 ./SIMPLE/src/utils/comm
          cp simple_forked_process.f90 ./SIMPLE/src/utils/
          cp simple_forked_process_tester.f90 ./SIMPLE/src/utils/
          cd SIMPLE
          rm -rf build
          mkdir build
          cd build
          #debug mode
          #cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=debug ..
          cmake -G "Unix Makefiles" -D_WIN32=1 ..
          make -j install
          export SIMPLE_EMAIL="my.name@uni.edu"
          export SIMPLE_QSYS="local"
          export SIMPLE_PATH="$GITHUB_WORKSPACE/SIMPLE/build"
          export PATH="$SIMPLE_PATH/scripts:$SIMPLE_PATH/bin:$PATH"
          simple_test_units
          simple_test_install

#on: [push]
#
#jobs:
#
#  build:
#    runs-on: windows-latest # MSYS2 is primarily used on Windows runners
#    steps:
#    - uses: actions/checkout@v4 # Checkout your repository's code
#    - name: Setup MSYS2
#      uses: msys2/setup-msys2@v2
#      with:
#        # Define which MSYS2 subsystem to use (e.g., MINGW64, UCRT64, CLANG64)
#        msystem: MSYS
#        update: true 
#        # Install required packages using pacman
#        install: >-
#          msys2-devel
#          base-devel
#          msys2-runtime-devel
#          git
#          make
#          cmake
#          gcc
#
#    - name: Run build commands in MSYS2 shell
#      # Use the 'msys2 {0}' shell to execute subsequent commands within the MSYS2 environment
#      shell: msys2 {0} 
#      run: |
#        pacman -S libtiff fftw 
#        uname -a
#        gcc --version
#        gfortran --version
#        make --version
#        gcc -fopenmp --version
#
#    - name: Install packages
#      shell: msys2 {0} 
#      run: |
#           #mkdir -p /ucrt64/include
#           #cp fts.h /ucrt64/include/
#           #wget -O /ucrt64/include/fts.h  https://raw.githubusercontent.com/openbsd/src/master/include/fts.h
#           gcc -v -E -x c - < /dev/null
#           git clone https://github.com/hael/SIMPLE.git 
#           cd SIMPLE
#           rm -rf build
#           mkdir build
#           cd build
#           cmake -G "MSYS Makefiles" .. 
#           make -j install



# Template for Test interface
#name: CI
#on: [push]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: mkdir -p build && wget -P build https://www.dartmouth.edu/emlab/images/hibim4.jpg 
#      - run: echo "<html><body><h1>SIMPLE Test Report</h1><p>Test Passed</p> <img src="hibim4.jpg" alt="Embedded Base64 image" width="100" height="100"> </body></html>" > build/artifact.html 
#      - uses: actions/upload-artifact@v4
#        with:
#          name: my-artifact
#          path: build/ 
